# permissions for end users to edit versionizers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: versionizer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s
    app.kubernetes.io/part-of: k8s
    app.kubernetes.io/managed-by: kustomize
  name: versionizer-editor-role
rules:
- apiGroups:
  - mepflix.iss.ch.my.domain
  resources:
  - versionizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mepflix.iss.ch.my.domain
  resources:
  - versionizers/status
  verbs:
  - get
